import localFont from "next/font/local";
import Menu from "./components/menu/menu";
import "./globals.css";

const spaceGrotesk = localFont({
  src: [
    {
      path: "./assets/fonts/SpaceGrotesk-Light.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "./assets/fonts/SpaceGrotesk-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./assets/fonts/SpaceGrotesk-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./assets/fonts/SpaceGrotesk-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-space-grotesk",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${spaceGrotesk.variable}`}>
        <Menu />
        {children}
      </body>
    </html>
  );
}
